spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: postgres
    password: admin
  jpa:
    query:
      name: Query
      description: GraphQL Query Schema Description
      use-distinct-parameter: true
      enabled: true
      path: /graphql
    properties:
      hibernate:
        types:
          print_banner: true
          databaseZone: UTC
          detectedDialect: POSTGRESQL
          legacy_compatibility: true

